"use client"

import FuzzyText from "@/components/FuzzyText"

const CODING_REFERENCES = [
  "git commit -m 'fixed'",
  "rm -rf node_modules",
  "// TODO: fix this later",
  "const [state, setState] = useState()",
  "export default function App() {",
  "console.log('debug')",
  "npm install",
  "return <div>{children}</div>",
  "null && <Component />",
  "const {} = props",
  "useEffect(() => {}, [])",
  "import React from 'react'",
  "className={`bg-${color}`}",
  "e.preventDefault()",
  "window.scrollTo(0, 0)",
  "localStorage.getItem('token')",
  "fetch('/api/data')",
  "await Promise.all()",
  "try { } catch (e) { }",
  "array.map((item) => <Item key={item.id} />)",
  "|| ''",
  "?? 'default'",
  "?.property",
  "process.env.VAR",
  "#region feature",
  "@ts-ignore",
  "// @ts-expect-error",
  "type Props = {}",
  "interface Props {}",
  "export type Type = {}",
  "<div className=''></div>",
  "const memoized = useMemo(() => fn(), [deps])",
  "useCallback(() => {}, [deps])",
  "useRef(initialValue)",
  "useReducer(reducer, initialState)",
  "useContext(Context)",
  "createContext(defaultValue)",
  "useEffect(() => { return cleanup }, [])",
  "throw new Error()",
  "const isLoading = true",
  "if (error) return null",
  "const data = await response.json()",
  "setIsLoading(false)",
  "setData(result)",
  "const [count, setCount] = useState(0)",
  "setCount(count + 1)",
  "useEffect(() => { init() }, [])",
  "const [mounted, setMounted] = useState(false)",
  "useEffect(() => setMounted(true), [])",
  "if (!mounted) return null",
  "useRouter()",
  "router.push('/path')",
  "router.back()",
  "useSearchParams()",
  "searchParams.get('id')",
  "usePathname()",
  "pathname === '/route'",
  "useSearchParams()",
  "params.id",
  "const query = supabase.from('table').select()",
  "const { data, error } = useSWR('/api')",
  "const { data, isLoading } = useQuery('key', fetcher)",
  "mutation.mutate({ id })",
  "queryClient.invalidateQueries(['key'])",
  "useMutation({ mutationFn, onSuccess })",
  "const toast = useToast()",
  "toast({ title, description })",
  "FormProvider",
  "useForm({ defaultValues })",
  "form.handleSubmit(onSubmit)",
  "form.register('name')",
  "form.watch('field')",
  "z.object({ name: z.string() })",
  "zod.parse(data)",
  "const schema = z.object({})",
  "new URLSearchParams()",
  "history.pushState(null, '', url)",
  "window.history.pushState()",
  "location.href = '/path'",
  "window.location.reload()",
  "document.title = 'Title'",
  "meta[name='description']",
  "link[rel='canonical']",
  "next/link",
  "next/image",
  "next/font",
  "getServerSideProps()",
  "getStaticProps()",
  "generateMetadata()",
  "export const metadata = {}",
  "export const dynamic = 'force-static'",
  "export const revalidate = 3600",
  "headers()",
  "cookies()",
  "getLayout()",
  "export default function RootLayout() {}",
  "export default async function Page() {}",
  "Suspense fallback={<Loading />}",
  "Error fallback={<ErrorPage />}",
  "notFound()",
  "redirect('/login')",
  "permanentRedirect('/new-path')",
  "useSession()",
  "getSession()",
  "signIn('credentials')",
  "signOut()",
  "useAuth()",
  "auth({ required: true })",
  "middleware.ts",
  "NextResponse.json()",
  "NextResponse.redirect()",
  "new Response('text', { status })",
  "Request.json()",
  "await request.json()",
  "request.headers.get()",
  "new Headers({ ...headers })",
  "Response.prototype.blob()",
  "Response.prototype.text()",
  "Response.prototype.json()",
  "const stream = new ReadableStream()",
  "const reader = stream.getReader()",
  "await reader.read()",
  "TextDecoder().decode()",
  "Uint8Array.from(str)",
  "ArrayBuffer",
  "TypedArray",
  "Float32Array",
  "Int32Array",
  "Uint8ClampedArray",
  "DataView",
  "buffer.buffer",
  "byteLength",
  "byteOffset",
  "SharedArrayBuffer",
  "Atomics.wait()",
  "Atomics.notify()",
  "Worker.postMessage()",
  "worker.onmessage = (e) => {}",
  "Blob([data], { type })",
  "URL.createObjectURL(blob)",
  "new WebSocket(url)",
  "ws.onopen = () => {}",
  "ws.onmessage = (e) => {}",
  "ws.send(JSON.stringify(data))",
  "ws.close()",
  "new EventSource(url)",
  "es.onmessage = (e) => {}",
  "es.addEventListener('event', (e) => {})",
  "es.close()",
  "navigator.geolocation.getCurrentPosition()",
  "Notification.requestPermission()",
  "new Notification(title, options)",
  "ServiceWorkerRegistration",
  "navigator.serviceWorker.register()",
  "CacheStorage.open()",
  "cache.put(request, response)",
  "cache.match(request)",
  "IndexedDB.open()",
  "transaction.oncomplete = () => {}",
  "request.onupgradeneeded = () => {}",
  "request.onsuccess = () => {}",
  "CanvasRenderingContext2D",
  "ctx.beginPath()",
  "ctx.moveTo(x, y)",
  "ctx.lineTo(x, y)",
  "ctx.stroke()",
  "ctx.fillStyle = 'rgba()'",
  "ctx.fillRect(x, y, w, h)",
  "ctx.arc(x, y, r, 0, Math.PI * 2)",
  "ctx.createImageData(w, h)",
  "putImageData(imageData, 0, 0)",
  "requestAnimationFrame(loop)",
  "cancelAnimationFrame(id)",
  "performance.now()",
  "performance.mark()",
  "performance.measure()",
  "ResizeObserver",
  "observer.observe(element)",
  "IntersectionObserver",
  "observer.observe(element)",
  "MutationObserver",
  "observer.observe(element, config)",
  "requestIdleCallback(callback)",
  "requestAnimationFrame()",
  "queueMicrotask(callback)",
  "Promise.resolve().then(callback)",
  "setTimeout(callback, delay)",
  "clearTimeout(id)",
  "setInterval(callback, interval)",
  "clearInterval(id)",
  "structuredClone(obj)",
  "WeakMap",
  "WeakSet",
  "FinalizationRegistry",
  "Symbol()",
  "Symbol.iterator",
  "Symbol.asyncIterator",
  "Proxy(target, handler)",
  "Reflect.apply()",
  "Object.freeze()",
  "Object.seal()",
  "Object.preventExtensions()",
  "Object.defineProperty()",
  "Object.getOwnPropertyDescriptor()",
  "Object.getOwnPropertyNames()",
  "Object.keys(obj)",
  "Object.values(obj)",
  "Object.entries(obj)",
  "Object.fromEntries()",
  "Object.assign({}, obj)",
  "Object.create(proto)",
  "Object.getPrototypeOf(obj)",
  "Object.setPrototypeOf(obj, proto)",
  "Array.from(iterable)",
  "Array.isArray(value)",
  "Array.of(...items)",
  "Array.prototype.flat()",
  "Array.prototype.flatMap()",
  "Array.prototype.reduce()",
  "Array.prototype.reduceRight()",
  "Array.prototype.filter()",
  "Array.prototype.find()",
  "Array.prototype.findIndex()",
  "Array.prototype.some()",
  "Array.prototype.every()",
  "Array.prototype.includes()",
  "Array.prototype.indexOf()",
  "Array.prototype.lastIndexOf()",
  "Array.prototype.map()",
  "Array.prototype.forEach()",
  "Array.prototype.slice()",
  "Array.prototype.splice()",
  "Array.prototype.push()",
  "Array.prototype.pop()",
  "Array.prototype.shift()",
  "Array.prototype.unshift()",
  "Array.prototype.sort()",
  "Array.prototype.reverse()",
  "Array.prototype.join()",
  "Array.prototype.concat()",
  "Array.prototype.flat()",
  "Array.prototype.toReversed()",
  "Array.prototype.toSorted()",
  "Array.prototype.toSpliced()",
  "Array.prototype.with()",
  "Map.prototype.get(key)",
  "Map.prototype.set(key, value)",
  "Map.prototype.has(key)",
  "Map.prototype.delete(key)",
  "Map.prototype.forEach()",
  "Map.prototype.entries()",
  "Map.prototype.keys()",
  "Map.prototype.values()",
  "Set.prototype.add(value)",
  "Set.prototype.has(value)",
  "Set.prototype.delete(value)",
  "Set.prototype.forEach()",
  "String.prototype.includes()",
  "String.prototype.startsWith()",
  "String.prototype.endsWith()",
  "String.prototype.match(regex)",
  "String.prototype.replace()",
  "String.prototype.replaceAll()",
  "String.prototype.split()",
  "String.prototype.trim()",
  "String.prototype.toLowerCase()",
  "String.prototype.toUpperCase()",
  "Number.isFinite()",
  "Number.isInteger()",
  "Number.isNaN()",
  "Number.parseFloat()",
  "Number.parseInt()",
  "Math.floor()",
  "Math.ceil()",
  "Math.round()",
  "Math.trunc()",
  "Math.abs()",
  "Math.pow()",
  "Math.sqrt()",
  "Math.random()",
  "Math.max()",
  "Math.min()",
  "Math.sin()",
  "Math.cos()",
  "Math.tan()",
  "Math.PI",
  "Math.E",
  "BigInt(value)",
  "BigInt.prototype.toString()",
  "globalThis",
  "global",
  "global",
  "window",
  "self",
  "document",
  "navigator",
  "history",
  "location",
  "console",
  "performance",
  "requestIdleCallback",
  "cancelIdleCallback(id)",
]

function getRandomReference() {
  return CODING_REFERENCES[Math.floor(Math.random() * CODING_REFERENCES.length)]
}

export default function NotFound() {
  const reference = getRandomReference()

  return (
    <main className="min-h-screen flex flex-col items-center justify-center px-4">
      <div className="text-center space-y-8">
        <FuzzyText
          fontSize={window.innerWidth < 768 ? 120 : 200}
          fontWeight={900}
          baseIntensity={0.3}
          fuzzRange={40}
          className="font-bold text-white"
        >
          404
        </FuzzyText>

        <div className="space-y-2">
          <p className="text-foreground/60 text-sm md:text-base font-mono">
            {reference}
          </p>
        </div>

        <div className="flex flex-col items-center justify-center gap-4">
          <button className="group/btn relative rounded-full bg-primary px-8 py-3 text-primary-foreground transition-all duration-[120ms] ease-out hover:scale-105 hover:shadow-lg active:scale-95">
            <span className="relative z-10 font-semibold">Go Home</span>
            <span className="absolute inset-0 rounded-full bg-primary/20 blur-xl opacity-0 transition-opacity duration-[300ms] ease-out group-hover/btn:opacity-100" />
          </button>
        </div>
      </div>
    </main>
  )
}
